name: AI Tests Matrix

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

defaults:
  run:
    shell: bash

jobs:
  TestOllamaAI:
    name: Ollama
    strategy:
      fail-fast: false
      matrix:
        model:
          - 'deepseek-r1:1.5b'
          - 'deepseek-r1:7b'
          - 'deepseek-r1:8b'
          - 'deepseek-r1:14b'
          # - 'deepseek-r1:32b'
          # - 'deepseek-r1:70b'
          # - 'deepseek-r1:671b'
          - 'gemma3:1b'
          - 'gemma3:4b'
          - 'gemma3:12b'    # google
          # - 'gemma3:27b'
          - 'phi3:14b'      # microsoft
          - 'phi3:3.8b'     
          - 'mixtral:8x7b'  # 26Gb, A set of Mixture of Experts (MoE) model with open weights by Mistral AI in 8x7b and 8x22b parameter sizes.
          # - 'mixtral:8x22b' # 79Gb
          - 'mistral-nemo:12b'    # A state-of-the-art 12B model with 128k context length, built by Mistral AI in collaboration with NVIDIA.
          - 'phuzzy/darkllama3.1' # Llama 3.1 8B Q8.0 - Uncensored with a penchant for infamy.
          
          


    runs-on: ubuntu-24.04
    timeout-minutes: 360
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Start ollama
      run: |
        set -eu -o pipefail;
        mkdir -p "${{ runner.temp }}/Artifacts"
        script=https://raw.githubusercontent.com/devizer/test-and-build/master/install-build-tools-bundle.sh; (wget -q -nv --no-check-certificate -O - $script 2>/dev/null || curl -ksSL $script) | bash > /dev/null
        cat /etc/docker/daemon.json || true
        sudo rm -rf /var/lib/docker
        echo '{ "data-root": "/mnt/docker" }' | sudo tee /etc/docker/daemon.json
        try-and-retry sudo systemctl restart docker

        Say "Creating swap /swap 23Gb"
        file=/swap
        time sudo dd if=/dev/zero of=$file bs=$((1024*1024)) count=23000
        sudo chmod 600 $file
        sudo mkswap $file
        sudo swapon $file
        # Say "Creating swap /mnt/swap 8Gb"
        # file=/mnt/swap
        # time sudo dd if=/dev/zero of=$file bs=$((1024*1024)) count=8000
        # sudo chmod 600 $file
        # sudo mkswap $file
        # sudo swapon $file

        df -h -T
        try-and-retry docker pull ollama/ollama
        docker run -d --name ollama -p 11434:11434 ollama/ollama

    - name: Pull ${{ matrix.model }}
      run: |
        set -eu -o pipefail;
        docker exec ollama bash -c "ollama pull ${{ matrix.model }} | cat"

    - name: API/TAGS ${{ matrix.model }}
      run: |
        set -eu -o pipefail;
        curl http://localhost:11434/api/tags | jq . | tee "${{ runner.temp }}/Artifacts/api-tags.json"

    - name: API/SHOW ${{ matrix.model }}
      run: |
        set -eu -o pipefail;
        curl http://localhost:11434/api/show -d '
        {
          "model": "${{ matrix.model }}",
          "verbose": false
        }
        ' | jq . | tee "${{ runner.temp }}/Artifacts/api-show.json"

    - name: 'ASK "8845HS vs 12700H"'
      run: |
        set -eu -o pipefail;
        bash ask.sh "${{ matrix.model }}" "8845HS vs 12700H" | tee "${{ runner.temp }}/Artifacts/ask-1-short.txt"

    - name: 'ASK "Compare AMD Ryzen 8845HS vs Intel i7-12700H. Also use specification from cpu-world.com"'
      run: |
        set -eu -o pipefail;
        bash ask.sh "${{ matrix.model }}" "Compare AMD Ryzen 8845HS vs Intel i7-12700H. Also use specification from cpu-world.com" | tee "${{ runner.temp }}/Artifacts/ask-2-detailed.txt"
    
    - name: 'System Info'
      if: always()
      run: |
        set -eu -o pipefail;
        Say "Free Memory"
        free -m
        Say "Free Space"
        df -h -T
        Say "System Stat"
        Show-System-Stat | tee "${{ runner.temp }}/Artifacts/System-Info.log"
          
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: 'Model ${{ matrix.model }}'
        path: '${{ runner.temp }}/Artifacts'

  Combine:
    name: Combine results in a single Artifact
    needs: [TestOllamaAI]
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: '**'
        path: "${{ runner.temp }}/Combined"
        merge-multiple: false

    - name: Show Download Structure
      run: 'sudo apt-get update -qq; sudo apt-get install tree -y -qq; tree $RUNNER_TEMP'

    - name: Upload Combined System Info
      uses: actions/upload-artifact@v4
      with:
        name: 'Combined CPU Usage Tests'
        path: "${{ runner.temp }}/Combined"

